{"timestamp": "2025-06-14 21:28:54,357", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:30:35,052", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:30:36,101", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:31:38,362", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:31:39,480", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:31:54,888", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:31:56,053", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:31:56,379", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:31:57,317", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:32:41,436", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:32:42,526", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:33:17,120", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:33:18,279", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:34:49,425", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:34:50,562", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:34:53,767", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.29, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:34:53,905", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 3.52, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:34:56,561", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 19.15, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:37:12,636", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:37:13,911", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:37:17,746", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.26, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:37:17,863", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 4.06, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:37:22,534", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 24.42, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:37:39,633", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: User not found.", "method": "GET", "url": "http://127.0.0.1:8000/users/2", "status_code": 404, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:37:39,633", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/2", "status_code": 404, "process_time_ms": 5.46, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:42:08,072", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.43, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:42:08,169", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 0.25, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 21:45:19,793", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:45:21,018", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 21:46:06,684", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 21:46:07,856", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:08:59,096", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:09:00,294", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:10:10,084", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:10:11,042", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:10:40,171", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:10:41,097", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:11:26,532", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:11:27,568", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:11:54,732", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:11:55,745", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:12:24,044", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:14:26,815", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:14:44,542", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:14:45,699", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:14:49,629", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:22:57,340", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:23:02,265", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.23, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:23:02,391", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 7.32, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:23:16,806", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedColumnError'>: column users.hashed_password does not exist\n[SQL: SELECT users.id, users.name, users.email, users.hashed_password \nFROM users]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 521, in _prepare_and_execute\n    prepared_stmt, attributes = await adapt_connection._prepare(\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        operation, self._invalidate_schema_cache_asof\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 768, in _prepare\n    prepared_stmt = await self._connection.prepare(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        operation, name=self._prepared_statement_name_func()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\asyncpg\\connection.py\", line 635, in prepare\n    return await self._prepare(\n           ^^^^^^^^^^^^^^^^^^^^\n    ...<5 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\asyncpg\\connection.py\", line 653, in _prepare\n    stmt = await self._get_statement(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<5 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\asyncpg\\connection.py\", line 432, in _get_statement\n    statement = await self._protocol.prepare(\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<5 lines>...\n    )\n    ^\n  File \"asyncpg\\\\protocol\\\\protocol.pyx\", line 165, in prepare\nasyncpg.exceptions.UndefinedColumnError: column users.hashed_password does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1963, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 943, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 580, in execute\n    self._adapt_connection.await_(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self._prepare_and_execute(operation, parameters)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 558, in _prepare_and_execute\n    self._handle_exception(error)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 508, in _handle_exception\n    self._adapt_connection._handle_exception(error)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 792, in _handle_exception\n    raise translated_error from error\nsqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedColumnError'>: column users.hashed_password does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\user.py\", line 52, in list_users\n    users = await service.get_all_users()\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\user_service.py\", line 36, in get_all_users\n    users_orm = await self.repository.get_all()\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\repositories\\user_repository.py\", line 20, in get_all\n    result = await self.session.execute(select(UserORM))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\ext\\asyncio\\session.py\", line 463, in execute\n    result = await greenlet_spawn(\n             ^^^^^^^^^^^^^^^^^^^^^\n    ...<6 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2365, in execute\n    return self._execute_internal(\n           ~~~~~~~~~~~~~~~~~~~~~~^\n        statement,\n        ^^^^^^^^^^\n    ...<4 lines>...\n        _add_event=_add_event,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2251, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self,\n        ^^^^^\n    ...<4 lines>...\n        conn,\n        ^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\context.py\", line 306, in orm_execute_statement\n    result = conn.execute(\n        statement, params or {}, execution_options=execution_options\n    )\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1415, in execute\n    return meth(\n        self,\n        distilled_parameters,\n        execution_options or NO_OPTIONS,\n    )\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 523, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self, distilled_params, execution_options\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1637, in _execute_clauseelement\n    ret = self._execute_context(\n        dialect,\n    ...<8 lines>...\n        cache_hit=cache_hit,\n    )\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1842, in _execute_context\n    return self._exec_single_context(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^\n        dialect, context, statement, parameters\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1982, in _exec_single_context\n    self._handle_dbapi_exception(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        e, str_statement, effective_parameters, cursor, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2351, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1963, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 943, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 580, in execute\n    self._adapt_connection.await_(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self._prepare_and_execute(operation, parameters)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 558, in _prepare_and_execute\n    self._handle_exception(error)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 508, in _handle_exception\n    self._adapt_connection._handle_exception(error)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\sqlalchemy\\dialects\\postgresql\\asyncpg.py\", line 792, in _handle_exception\n    raise translated_error from error\nsqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedColumnError'>: column users.hashed_password does not exist\n[SQL: SELECT users.id, users.name, users.email, users.hashed_password \nFROM users]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "method": "GET", "url": "http://127.0.0.1:8000/users/", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:23:52,535", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:23:53,502", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:28:11,366", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:28:54,820", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:29:13,733", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 17.73, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:29:30,326", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 8.67, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:29:40,019", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: UserRepository.__init__() missing 1 required positional argument: 'session'", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n    |     solved_result = await solve_dependencies(\n    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<6 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 640, in solve_dependencies\n    |     solved = await run_in_threadpool(call, **solved_result.values)\n    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\concurrency.py\", line 37, in run_in_threadpool\n    |     return await anyio.to_thread.run_sync(func)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    |     return await get_async_backend().run_sync_in_worker_thread(\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |         func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter\n    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2470, in run_sync_in_worker_thread\n    |     return await future\n    |            ^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 967, in run\n    |     result = context.run(func, *args)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 13, in get_auth_service\n    |     user_repo = UserRepository()\n    | TypeError: UserRepository.__init__() missing 1 required positional argument: 'session'\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n    solved_result = await solve_dependencies(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<6 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 640, in solve_dependencies\n    solved = await run_in_threadpool(call, **solved_result.values)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\concurrency.py\", line 37, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2470, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 967, in run\n    result = context.run(func, *args)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 13, in get_auth_service\n    user_repo = UserRepository()\nTypeError: UserRepository.__init__() missing 1 required positional argument: 'session'", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:30:05,787", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:30:06,696", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:31:29,239", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:31:30,469", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:32:01,571", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:37:48,983", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:37:59,732", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.23, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:37:59,835", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.04, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:38:03,349", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 11.3, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:38:12,776", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:38:12,777", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 9.22, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:38:29,363", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:38:29,364", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 5.01, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:39:02,252", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: hash could not be identified", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    |     raw_response = await run_endpoint_function(\n    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<3 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    |     user = await auth_service.authenticate_user(credentials.email, credentials.password)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 44, in authenticate_user\n    |     if not self.verify_password(password, user_orm.hashed_password):\n    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 26, in verify_password\n    |     return pwd_context.verify(plain_password, hashed_password)\n    |            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    |     record = self._get_or_identify_record(hash, scheme, category)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    |     return self._identify_record(hash, category)\n    |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    |     raise exc.UnknownHashError(\"hash could not be identified\")\n    | passlib.exc.UnknownHashError: hash could not be identified\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    user = await auth_service.authenticate_user(credentials.email, credentials.password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 44, in authenticate_user\n    if not self.verify_password(password, user_orm.hashed_password):\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 26, in verify_password\n    return pwd_context.verify(plain_password, hashed_password)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    record = self._get_or_identify_record(hash, scheme, category)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    return self._identify_record(hash, category)\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    raise exc.UnknownHashError(\"hash could not be identified\")\npasslib.exc.UnknownHashError: hash could not be identified", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:39:49,918", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:39:51,365", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:39:52,121", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:39:53,024", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:40:11,276", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:40:12,458", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:40:14,504", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:40:15,442", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:40:19,599", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.31, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:40:19,711", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 4.19, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:40:23,003", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: hash could not be identified", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    |     raw_response = await run_endpoint_function(\n    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<3 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    |     user = await auth_service.authenticate_user(credentials.email, credentials.password)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    |     if not self.verify_password(password, user_orm.hashed_password):\n    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    |     return verify_password(plain_password, hashed_password)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    |     return pwd_context.verify(plain_password, hashed_password)\n    |            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    |     record = self._get_or_identify_record(hash, scheme, category)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    |     return self._identify_record(hash, category)\n    |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    |     raise exc.UnknownHashError(\"hash could not be identified\")\n    | passlib.exc.UnknownHashError: hash could not be identified\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    user = await auth_service.authenticate_user(credentials.email, credentials.password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    if not self.verify_password(password, user_orm.hashed_password):\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    return verify_password(plain_password, hashed_password)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    return pwd_context.verify(plain_password, hashed_password)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    record = self._get_or_identify_record(hash, scheme, category)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    return self._identify_record(hash, category)\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    raise exc.UnknownHashError(\"hash could not be identified\")\npasslib.exc.UnknownHashError: hash could not be identified", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:40:29,263", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:40:30,172", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:40:35,489", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: hash could not be identified", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    |     raw_response = await run_endpoint_function(\n    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<3 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    |     user = await auth_service.authenticate_user(credentials.email, credentials.password)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    |     if not self.verify_password(password, user_orm.hashed_password):\n    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    |     return verify_password(plain_password, hashed_password)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    |     return pwd_context.verify(plain_password, hashed_password)\n    |            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    |     record = self._get_or_identify_record(hash, scheme, category)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    |     return self._identify_record(hash, category)\n    |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    |     raise exc.UnknownHashError(\"hash could not be identified\")\n    | passlib.exc.UnknownHashError: hash could not be identified\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    user = await auth_service.authenticate_user(credentials.email, credentials.password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    if not self.verify_password(password, user_orm.hashed_password):\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    return verify_password(plain_password, hashed_password)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    return pwd_context.verify(plain_password, hashed_password)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    record = self._get_or_identify_record(hash, scheme, category)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    return self._identify_record(hash, category)\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    raise exc.UnknownHashError(\"hash could not be identified\")\npasslib.exc.UnknownHashError: hash could not be identified", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:41:12,666", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:41:13,758", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:42:36,292", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.37, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:42:36,400", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.5, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:42:41,605", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 13.99, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:42:50,237", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: hash could not be identified", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    |     raw_response = await run_endpoint_function(\n    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<3 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    |     user = await auth_service.authenticate_user(credentials.email, credentials.password)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    |     if not self.verify_password(password, user_orm.hashed_password):\n    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    |     return verify_password(plain_password, hashed_password)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    |     return pwd_context.verify(plain_password, hashed_password)\n    |            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    |     record = self._get_or_identify_record(hash, scheme, category)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    |     return self._identify_record(hash, category)\n    |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    |     raise exc.UnknownHashError(\"hash could not be identified\")\n    | passlib.exc.UnknownHashError: hash could not be identified\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    user = await auth_service.authenticate_user(credentials.email, credentials.password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    if not self.verify_password(password, user_orm.hashed_password):\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    return verify_password(plain_password, hashed_password)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    return pwd_context.verify(plain_password, hashed_password)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    record = self._get_or_identify_record(hash, scheme, category)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    return self._identify_record(hash, category)\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    raise exc.UnknownHashError(\"hash could not be identified\")\npasslib.exc.UnknownHashError: hash could not be identified", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:42:58,055", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: hash could not be identified", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    |     response = await f(request)\n    |                ^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    |     raw_response = await run_endpoint_function(\n    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |     ...<3 lines>...\n    |     )\n    |     ^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    |     user = await auth_service.authenticate_user(credentials.email, credentials.password)\n    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    |     if not self.verify_password(password, user_orm.hashed_password):\n    |            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    |     return verify_password(plain_password, hashed_password)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    |     return pwd_context.verify(plain_password, hashed_password)\n    |            ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    |     record = self._get_or_identify_record(hash, scheme, category)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    |     return self._identify_record(hash, category)\n    |            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    |     raise exc.UnknownHashError(\"hash could not be identified\")\n    | passlib.exc.UnknownHashError: hash could not be identified\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\routers\\auth.py\", line 23, in login\n    user = await auth_service.authenticate_user(credentials.email, credentials.password)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 41, in authenticate_user\n    if not self.verify_password(password, user_orm.hashed_password):\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\services\\auth_service.py\", line 23, in verify_password\n    return verify_password(plain_password, hashed_password)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\core\\password_hashing.py\", line 11, in verify_password\n    return pwd_context.verify(plain_password, hashed_password)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2343, in verify\n    record = self._get_or_identify_record(hash, scheme, category)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 2031, in _get_or_identify_record\n    return self._identify_record(hash, category)\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\passlib\\context.py\", line 1132, in identify_record\n    raise exc.UnknownHashError(\"hash could not be identified\")\npasslib.exc.UnknownHashError: hash could not be identified", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:43:24,943", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:43:26,164", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:43:33,235", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:43:34,162", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:43:43,467", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:43:44,500", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:43:52,027", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:43:53,117", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:44:20,765", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:44:21,806", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:44:24,520", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:44:25,633", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:44:47,171", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.43, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:00,218", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.99, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:00,465", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 4.09, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:05,569", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:45:08,533", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:45:12,076", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.24, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:12,144", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.81, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:14,937", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 13.02, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:23,900", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/4", "status_code": 200, "process_time_ms": 6.21, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:36,160", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:36,160", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 11.05, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:43,220", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:45:43,221", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 4.16, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:47:15,017", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/users/", "status_code": 201, "process_time_ms": 435.9, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:48:38,362", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 200, "process_time_ms": 228.15, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:52:48,405", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:53:11,221", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:53:56,613", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:55:24,823", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:55:24,924", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:55:26,191", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-14 22:55:39,852", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.27, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:55:39,965", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.2, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:55:43,273", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.45, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:55:43,343", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 0.33, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:55:45,467", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 13.83, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:56:17,331", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:56:17,332", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 7.71, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-14 22:56:21,001", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-14 22:56:21,996", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:42:14,290", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.91, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:42:14,413", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 17.12, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:42:26,140", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 46.85, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:44:58,659", "level": "WARNING", "name": "pep2-backend", "message": "Validation error: [{'type': 'model_attributes_type', 'loc': ('body',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': b'grant_type=password&username=d%40k.ro&password=d'}]", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:44:58,660", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: Object of type bytes is not JSON serializable", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 59, in wrapped_app\n    |     response = await handler(conn, exc)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 93, in validation_exception_handler\n    |     return JSONResponse(\n    |         status_code=422,\n    |         content={\"detail\": exc.errors()}\n    |     )\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 182, in __init__\n    |     super().__init__(content, status_code, headers, media_type, background)\n    |     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 45, in __init__\n    |     self.body = self.render(content)\n    |                 ~~~~~~~~~~~^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 185, in render\n    |     return json.dumps(\n    |            ~~~~~~~~~~^\n    |         content,\n    |         ^^^^^^^^\n    |     ...<3 lines>...\n    |         separators=(\",\", \":\"),\n    |         ^^^^^^^^^^^^^^^^^^^^^^\n    |     ).encode(\"utf-8\")\n    |     ^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\__init__.py\", line 238, in dumps\n    |     **kw).encode(obj)\n    |           ~~~~~~^^^^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 200, in encode\n    |     chunks = self.iterencode(o, _one_shot=True)\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 261, in iterencode\n    |     return _iterencode(o, 0)\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 180, in default\n    |     raise TypeError(f'Object of type {o.__class__.__name__} '\n    |                     f'is not JSON serializable')\n    | TypeError: Object of type bytes is not JSON serializable\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 59, in wrapped_app\n    response = await handler(conn, exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 93, in validation_exception_handler\n    return JSONResponse(\n        status_code=422,\n        content={\"detail\": exc.errors()}\n    )\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 182, in __init__\n    super().__init__(content, status_code, headers, media_type, background)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 45, in __init__\n    self.body = self.render(content)\n                ~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 185, in render\n    return json.dumps(\n           ~~~~~~~~~~^\n        content,\n        ^^^^^^^^\n    ...<3 lines>...\n        separators=(\",\", \":\"),\n        ^^^^^^^^^^^^^^^^^^^^^^\n    ).encode(\"utf-8\")\n    ^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ~~~~~~^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 261, in iterencode\n    return _iterencode(o, 0)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\n                    f'is not JSON serializable')\nTypeError: Object of type bytes is not JSON serializable", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:45:03,121", "level": "WARNING", "name": "pep2-backend", "message": "Validation error: [{'type': 'model_attributes_type', 'loc': ('body',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': b'grant_type=password&username=d%40k.ro&password=d'}]", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:45:03,121", "level": "ERROR", "name": "pep2-backend", "message": "Unhandled exception: Object of type bytes is not JSON serializable", "exc_info": "  + Exception Group Traceback (most recent call last):\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 76, in collapse_excgroups\n  |     yield\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 177, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                ~~~~~~~~~~~~~~~~~~~~~~~^^\n  |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |         \"unhandled errors in a TaskGroup\", self._exceptions\n  |     ) from None\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    |     await self.app(scope, receive, _send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |                                    ~~~~~~~~~~~~~~~~~~^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    |     self.gen.throw(value)\n    |     ~~~~~~~~~~~~~~^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    |     response = await call_next(request)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    |     raise app_exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    |     await route.handle(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    |     await self.app(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 59, in wrapped_app\n    |     response = await handler(conn, exc)\n    |                ^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 93, in validation_exception_handler\n    |     return JSONResponse(\n    |         status_code=422,\n    |         content={\"detail\": exc.errors()}\n    |     )\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 182, in __init__\n    |     super().__init__(content, status_code, headers, media_type, background)\n    |     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 45, in __init__\n    |     self.body = self.render(content)\n    |                 ~~~~~~~~~~~^^^^^^^^^\n    |   File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 185, in render\n    |     return json.dumps(\n    |            ~~~~~~~~~~^\n    |         content,\n    |         ^^^^^^^^\n    |     ...<3 lines>...\n    |         separators=(\",\", \":\"),\n    |         ^^^^^^^^^^^^^^^^^^^^^^\n    |     ).encode(\"utf-8\")\n    |     ^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\__init__.py\", line 238, in dumps\n    |     **kw).encode(obj)\n    |           ~~~~~~^^^^^\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 200, in encode\n    |     chunks = self.iterencode(o, _one_shot=True)\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 261, in iterencode\n    |     return _iterencode(o, 0)\n    |   File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 180, in default\n    |     raise TypeError(f'Object of type {o.__class__.__name__} '\n    |                     f'is not JSON serializable')\n    | TypeError: Object of type bytes is not JSON serializable\n    +------------------------------------\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 176, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n                                   ~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_utils.py\", line 82, in collapse_excgroups\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 178, in __call__\n    response = await self.dispatch_func(request, call_next)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 44, in dispatch\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 156, in call_next\n    raise app_exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\base.py\", line 141, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 59, in wrapped_app\n    response = await handler(conn, exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\app\\main.py\", line 93, in validation_exception_handler\n    return JSONResponse(\n        status_code=422,\n        content={\"detail\": exc.errors()}\n    )\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 182, in __init__\n    super().__init__(content, status_code, headers, media_type, background)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 45, in __init__\n    self.body = self.render(content)\n                ~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Users\\adria\\Github\\po-pep-learning\\pep2-backend\\venv\\Lib\\site-packages\\starlette\\responses.py\", line 185, in render\n    return json.dumps(\n           ~~~~~~~~~~^\n        content,\n        ^^^^^^^^\n    ...<3 lines>...\n        separators=(\",\", \":\"),\n        ^^^^^^^^^^^^^^^^^^^^^^\n    ).encode(\"utf-8\")\n    ^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n          ~~~~~~^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 200, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 261, in iterencode\n    return _iterencode(o, 0)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\\Lib\\json\\encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\n                    f'is not JSON serializable')\nTypeError: Object of type bytes is not JSON serializable", "method": "POST", "url": "http://127.0.0.1:8000/login", "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:46:48,775", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:46:50,229", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:47:51,553", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:47:52,923", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:48:32,095", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:48:33,115", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:48:37,900", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.3, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:48:38,039", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 6.46, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:48:42,714", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Not authenticated", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:48:42,714", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 2.43, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:49:57,843", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:49:59,211", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:50:04,693", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:50:05,885", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:50:38,305", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:50:39,563", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:50:59,682", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.44, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:50:59,791", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.1, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:08,844", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Not authenticated", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 403, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:08,845", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 403, "process_time_ms": 2.2, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:15,561", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:15,561", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 17.53, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:23,594", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid email or password", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:23,594", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 401, "process_time_ms": 6.68, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:51:42,141", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 200, "process_time_ms": 324.67, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:03,162", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid authentication credentials", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:03,163", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 58.26, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:06,420", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid authentication credentials", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:06,421", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 1.75, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:36,427", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid authentication credentials", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:52:36,428", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 1.53, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:54:03,909", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:54:05,418", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:54:52,081", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:54:53,045", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:55:01,539", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/docs", "status_code": 200, "process_time_ms": 0.28, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:55:01,633", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/openapi.json", "status_code": 200, "process_time_ms": 5.1, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:55:14,242", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 200, "process_time_ms": 280.38, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:55:29,942", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid authentication credentials", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:55:29,942", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 6.78, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 07:56:15,505", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:56:17,037", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 07:56:35,212", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 07:56:36,226", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 10:11:52,568", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 200, "process_time_ms": 444.68, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:13:09,130", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 10:13:10,530", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 10:13:33,842", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Invalid authentication credentials", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:13:33,842", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 401, "process_time_ms": 6.14, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:15:39,152", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 10:15:40,528", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 10:15:55,899", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 10:15:57,147", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 10:16:41,257", "level": "INFO", "name": "pep2-backend", "message": "Application shutdown"}
{"timestamp": "2025-06-15 10:16:42,258", "level": "INFO", "name": "pep2-backend", "message": "Application startup: Creating database tables if not exist"}
{"timestamp": "2025-06-15 10:16:53,215", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 18.83, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:17:04,099", "level": "WARNING", "name": "pep2-backend", "message": "HTTPException: Not authenticated", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 403, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:17:04,100", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 403, "process_time_ms": 2.48, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:17:19,432", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "POST", "url": "http://127.0.0.1:8000/login", "status_code": 200, "process_time_ms": 463.89, "client_host": "127.0.0.1"}
{"timestamp": "2025-06-15 10:17:34,797", "level": "INFO", "name": "pep2-backend", "message": "HTTP request completed", "method": "GET", "url": "http://127.0.0.1:8000/users/", "status_code": 200, "process_time_ms": 15.25, "client_host": "127.0.0.1"}
